apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hcsg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-hcsg@sha256:944cf205ca85eb4057bfd6747859ecdf53143dd1c09fd400d519af6e9e68d8ec
        name: my-nodejs
        resources: {}
status: {}
